### ISSUE TITLE
Protect the DI

### ISSUE THREAD

**Issue by kfwerf** [smikodanic/angular-countries#1]
Hey, i tried using your code but im running into issues because you havent actually protected your DI,

e.g. https://github.com/smikodanic/angular-countries/blob/master/src/main.js#L44

should be `ngCountries.run([ '$templateCache', function ($templateCache) {}])`

Otherwise there should be some sort of `ngInject` added when building this for production.

I can fix it in a PR if you want, cheers!

**Comment by smikodanic** [comment]
Hi Kenneth, yes please do that. Thx

**Comment by kfwerf** [comment]
@smikodanic Hey see my PR here https://github.com/smikodanic/angular-countries/pull/2

Cheers!
